### ISSUE TITLE
Internal annotations

### ISSUE THREAD

**Issue by aivchen** [zlodes/php-prometheus-client#7]
Class `BaseMetric` has `@internal Zlodes\PrometheusExporter\Metric` annotation.

As a result psalm fails when I try to call `new Gauge(...)`, `new Counter(...)` or `new Histogram`. 

The same thing with `GaugeCollector`, `CounterCollector`, `HistogramCollector`. 

```php
new Gauge('body_temperature', 'Body temperature in Celsius'); //Constructor Zlodes\PrometheusClient\Metric\BaseMetric::__construct is internal to Zlodes and Zlodes but called from Andrew\Zlodes\Test::test
```

```php
$bodyTemperatureGauge
            ->withLabels(['source' => 'ass'])
            ->update(37.2); //The method Zlodes\PrometheusClient\Collector\ByType\GaugeCollector::update is internal to Zlodes and Zlodes but called from Andrew\Zlodes\Test::test
```

**Comment by zlodes** [comment]
Hi!

Yeap, I've already fixed it. I'm going to update it yesterday. Stay tune!

**Comment by zlodes** [comment]
@aivchen Hello again!
Could you please provide versions of:
- Psalm
- PHP

Seems I mentioned another issue.

Just tried it on fresh project and seems that it works fine.

**Comment by aivchen** [comment]
Hi!
```console
[andrew@manjaro php-prometheus-client]$ composer show --direct
vimeo/psalm              5.15.0 A static analysis tool for finding errors in PHP applications
zlodes/prometheus-client 1.1.4  The Prometheus Metrics client for PHP
[andrew@manjaro php-prometheus-client]$ php -v
PHP 8.2.9 (cli) (built: Aug  1 2023 12:25:51) (NTS)
```

>Just tried it on fresh project and seems that it works fine.

I've prepared a test project for you: https://github.com/aivchen/php-prometheus-client-test

```console
git clone https://github.com/aivchen/php-prometheus-client-test
cd php-prometheus-client-test
composer install
vendor/bin/psalm
```

**Comment by zlodes** [comment]
@aivchen Fixed. Thank you!
